# -*- coding: utf-8 -*-
"""Loan_payback_classifier_streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pfGSxFXVeGFjHfAaPmCwfVDo2q0w6O14
"""

!pip install streamlit
import streamlit as st
import pandas as pd
import joblib # Import joblib for loading the model
import numpy as np
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
import altair as alt # Import altair for custom chart colors


# Open the file and load the model, poly, scaler, and training_columns
file_to_load = 'loan_model_classifier1.pkl'
poly_file = 'poly.pkl'
scaler_file = 'scaler.pkl'
training_columns_file = 'training_predictors_columns.pkl'

try:
    with open(file_to_load, 'rb') as file:
        loaded_model = joblib.load(file)
    with open(poly_file, 'rb') as file:
        poly = joblib.load(file)
    with open(scaler_file, 'rb') as file:
        scaler = joblib.load(file)
    with open(training_columns_file, 'rb') as file:
        training_predictors_columns = joblib.load(file)
    st.success("Model and preprocessing objects loaded successfully!")
except FileNotFoundError as e:
    st.error(f"Error loading file: {e}. Please ensure '{e.filename}' exists in the environment.")
    st.stop() # Stop the app if essential files are missing
except Exception as e:
    st.error(f"An unexpected error occurred during loading: {e}")
    st.stop()


# --- Streamlit UI ---
st.set_page_config(page_title="💰 Bucknell Lending Club: Loan Outcome Predictor", layout="centered")

# Bucknell Colors
BUCKNELL_BLUE = "#002856"
BUCKNELL_ORANGE = "#D36C2F"

st.markdown(f"<h1 style='text-align: center; color: {BUCKNELL_BLUE};'>💰 Bucknell Lending Club: Loan Outcome Predictor</h1>", unsafe_allow_html=True)

st.image("bison.jpg", caption="Bucknell Bison", width=200)

st.markdown(f"<p style='text-align: center; color: {BUCKNELL_BLUE};'>Enter a potential loan customer's details to predict their loan outcome (Fully Paid or Charged Off).</p>", unsafe_allow_html=True)

# Use st.expander for better layout organization

with st.expander("Loan Details", expanded=True):
    loan_amnt = st.number_input("Loan Amount", min_value=0.0, max_value=50000.0, value=10000.0, step=100.0)
    funded_amnt = st.number_input("Funded Amount", min_value=0.0, max_value=50000.0, value=10000.0, step=100.0)
    int_rate = st.slider("Interest Rate (%)", min_value=0.0, max_value=30.0, value=15.0, step=0.1)
    installment = st.number_input("Installment", min_value=0.0, max_value=2000.0, value=300.0, step=10.0)
    term_num = st.selectbox("Term (months)", options=[36, 60], index=0)
    purpose = st.selectbox("Purpose", options=['car', 'credit_card', 'debt_consolidation', 'educational', 'home_improvement', 'house', 'major_purchase', 'medical', 'moving', 'other', 'renewable_energy', 'small_business', 'vacation', 'wedding'], index=2)
    grade = st.selectbox("Grade", options=['A', 'B', 'C', 'D', 'E', 'F', 'G'], index=1)

with st.expander("Borrower Details", expanded=True):
    income = st.slider("Annual Income", 20000, 1000000, 80000) # This is annual_inc
    dti = st.slider("Debt-to-Income Ratio", 0, 40, 10) # already exists
    fico = st.slider("FICO Score", 300, 850, 650) # already exists
    home_ownership = st.selectbox("Home Ownership", options=['MORTGAGE', 'OWN', 'RENT', 'OTHER', 'NONE'], index=1) # Replaced ownhome checkbox
    emp_length = st.selectbox("Employment Length", options=['< 1 year', '1 year', '2 years', '3 years', '4 years', '5 years', '6 years', '7 years', '8 years', '9 years', '10+ years'], index=10)
    verification_status = st.selectbox("Verification Status", options=['Not Verified', 'Source Verified', 'Verified'], index=1)
    delinq_2yrs = st.number_input("Delinquencies in Last 2 Years", min_value=0, max_value=20, value=0)
    open_acc = st.number_input("Number of Open Credit Lines", min_value=0, max_value=50, value=5)
    pub_rec = st.number_input("Number of Public Record Derogatories", min_value=0, max_value=20, value=0)
    revol_bal = st.number_input("Revolving Balance", min_value=0.0, max_value=100000.0, value=10000.0, step=100.0)
    revol_util = st.slider("Revolving Line Utilization (%)", min_value=0.0, max_value=100.0, value=50.0, step=0.1)

# Prediction button outside the expanders
if st.button("Predict Loan Outcome"):
    with st.expander("Prediction Output", expanded=True):
        # Create a dictionary of raw features from Streamlit inputs
        raw_customer_data_dict = {
            'loan_amnt': loan_amnt,
            'funded_amnt': funded_amnt,
            'int_rate': int_rate,
            'installment': installment,
            'dti': dti,
            'delinq_2yrs': delinq_2yrs,
            'open_acc': open_acc,
            'pub_rec': pub_rec,
            'fico_range_high': fico, # Use Streamlit fico for both
            'fico_range_low': fico,   # Use Streamlit fico for both
            'revol_bal': revol_bal,
            'revol_util': revol_util,
            'term_num': term_num,
            'annual_inc': income, # Map income to annual_inc
            'grade': grade,
            'emp_length': emp_length,
            'home_ownership': home_ownership,
            'verification_status': verification_status,
            'purpose': purpose
        }
        new_customer_raw_df = pd.DataFrame([raw_customer_data_dict])

        # --- Apply preprocessing steps as per training code ---

        # 1) Log transformation for annual_inc
        # Ensure annual_inc is not zero or negative before taking log
        new_customer_raw_df['annual_inc'] = new_customer_raw_df['annual_inc'].replace(0, np.nan).fillna(1) # Replace 0 with 1 to avoid log(0)
        new_customer_raw_df['log_annual_inc'] = np.log(new_customer_raw_df['annual_inc'])
        # Drop original annual_inc as log_annual_inc is used in the model
        new_customer_raw_df = new_customer_raw_df.drop(columns=['annual_inc'])

        # Define categorical columns as per training
        cat_cols = ['grade', 'emp_length', 'home_ownership', 'verification_status', 'purpose']

        # 2) One-Hot Encoding for categorical columns
        # Use pd.get_dummies and then reindex to ensure consistent columns as in training
        customer_encoded_df = pd.get_dummies(new_customer_raw_df, columns=cat_cols, prefix_sep='_', drop_first=True)

        # Ensure all training columns are present and in the correct order
        # Fill missing columns with 0, and drop any extra columns not in training data
        processed_df_aligned = customer_encoded_df.reindex(columns=training_predictors_columns, fill_value=0)

        # 3) Polynomial Transformation
        user_data_poly = poly.transform(processed_df_aligned)

        # 4) Standardization
        user_data_scaled = scaler.transform(user_data_poly)

        # Make Prediction
        predicted_prob = loaded_model.predict_proba(user_data_scaled)[:, 1]
        custom_threshold = 0.3 # You can change this value
        predicted_class = (predicted_prob >= custom_threshold).astype(int)

        # Format and Display results
        formatted_prob = f"{predicted_prob[0]:.2f}"

        st.write(f"Predicted Probability of Charged Off: **{formatted_prob}**")
        if predicted_class[0] == 1:
            st.markdown(f"<h3 style='color: {BUCKNELL_ORANGE};'>Predicted Class: **Charged Off**</h3>", unsafe_allow_html=True)
        else:
            st.markdown(f"<h3 style='color: {BUCKNELL_BLUE};'>Predicted Class: **Fully Paid**</h3>", unsafe_allow_html=True)

        # Show the default probability and not default as a pie chart with custom colors
        probabilities = [predicted_prob[0], 1 - predicted_prob[0]]
        outcomes = ['Charged Off', 'Fully Paid']
        chart_df = pd.DataFrame({'Outcome': outcomes, 'Probability': probabilities})

        # Define colors for the chart
        color_scale = alt.Scale(domain=['Charged Off', 'Fully Paid'], range=[BUCKNELL_ORANGE, BUCKNELL_BLUE])

        chart = alt.Chart(chart_df).mark_bar().encode(
            x=alt.X('Probability', axis=alt.Axis(format='.0%')), # Format as percentage
            y=alt.Y('Outcome', sort='-x'), # Sort bars by probability
            color=alt.Color('Outcome', scale=color_scale),
            tooltip=['Outcome', alt.Tooltip('Probability', format='.2%')])\
        .properties(
            title='Prediction Breakdown'
        )
        st.altair_chart(chart, use_container_width=True)

st.markdown("---")